sqlite: &sqlite
  adapter: sqlite3
  verbosity: quiet

postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: ember
  password: password

test:
  <<: *sqlite
  database: tmp/dbs/ember_devise_test.db

development:
  <<: *sqlite
  database: tmp/dbs/ember_devise_development.db

production:
  <<: *postgresql
  database: ember_devise_production